db:
  image: postgres:9.3
  volumes_from:
    - APP_NAME-db-data
  ports:
    - 5432
web:
  build: .
  command: bundle exec unicorn -p 3000 -c ./config/unicorn.rb
  volumes:
    - .:/usr/src/app
  volumes_from:
    - gems-RUBY_VERSION
  ports:
    - "3000:3000"
  links:
    - db
